[[language]]
name = "gotmpl"
file-types = ["tmpl"]

[[language]]
name = "python"
formatter = { command = 'ruff', args = ["format", "--quiet", "-"] }

[language-server]
zk-lsp = { command = "zk", args = ["lsp"] }

[[language]]
name = "markdown"
roots = [".zk"]
language-servers = ["zk-lsp"]
