set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'V' send -X select-line

set-option -g focus-events on

set-option -g renumber-windows on

set -sg escape-time 0

bind -n M-Left previous-window
bind -n M-Right next-window

bind -n M-n new-window

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

if -F "#{==:#{session_windows},1}" "set -g status off" "set -g status on"
set-hook -g window-linked 'if -F "#{==:#{session_windows},1}" "set -g status off" "set -g status on"'
set-hook -g window-unlinked 'if -F "#{==:#{session_windows},1}" "set -g status off" "set -g status on"'

set-option -g status-position bottom

set -g popup-border-lines 'rounded'
set -g @window-status-fg '#ffffff'
set -g @window-status-bg '#191919'
set -g @status-line-bg '#171717'
set -g status-bg '#1a1a1a'
set -g base-index 1
set -g pane-base-index 1
