save-position-on-quit=yes
rebase-start-time=no

# Video
hwdec=auto-safe
deband=yes
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation=yes
tscale=oversample

# Audio
af=scaletempo

# Subs
sub-auto=fuzzy
sub-font-size=36
sub-border-size=2
sub-shadow-offset=1

# UI
osc=yes
cursor-autohide=1000
idle=yes
screenshot-format=png
force-window=yes

# Streaming
ytdl-format=bestvideo+bestaudio/best
