# Playback
save-position-on-quit=yes
rebase-start-time=no

# Video
hwdec=auto-safe
deband=yes
video-sync=display-resample
## Scaling
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
## Interpolation
interpolation=yes
tscale=oversample

# Audio
af=scaletempo

# Subs
sub-auto=fuzzy

# UI
osc=yes
cursor-autohide=1000
idle=yes
screenshot-format=png
force-window=yes
