workspace 1 output "LG Display 0x0521 Unknown"
workspace 2 output "LG Display 0x0521 Unknown"
workspace 3 output "LG Display 0x0521 Unknown"
workspace 4 output "LG Display 0x0521 Unknown"
workspace 5 output "LG Display 0x0521 Unknown"
workspace 6 output "LG Display 0x0521 Unknown"
workspace 7 output "LG Display 0x0521 Unknown"
workspace 8 output "LG Display 0x0521 Unknown"
workspace 9 output "LG Display 0x0521 Unknown"
workspace 10 output "LG Display 0x0521 Unknown"

output "LG Display 0x0521 Unknown" {
  mode 1920x1080
  position 0,0
}

input "type:keyboard" {
  xkb_layout de
}

gaps inner 4
gaps outer 6
