workspace 21 output "DENON, Ltd. DENON-AVR 0000000000001"
workspace 22 output "DENON, Ltd. DENON-AVR 0000000000001"
workspace 23 output "DENON, Ltd. DENON-AVR 0000000000001"
workspace 24 output "DENON, Ltd. DENON-AVR 0000000000001"
workspace 25 output "DENON, Ltd. DENON-AVR 0000000000001"
workspace 26 output "DENON, Ltd. DENON-AVR 0000000000001"
workspace 27 output "DENON, Ltd. DENON-AVR 0000000000001"
workspace 28 output "DENON, Ltd. DENON-AVR 0000000000001"
workspace 29 output "DENON, Ltd. DENON-AVR 0000000000001"
workspace 30 output "DENON, Ltd. DENON-AVR 0000000000001"

workspace 11 output "Microstep Optix MAG27CQ 0000000000001"
workspace 12 output "Microstep Optix MAG27CQ 0000000000001"
workspace 13 output "Microstep Optix MAG27CQ 0000000000001"
workspace 14 output "Microstep Optix MAG27CQ 0000000000001"
workspace 15 output "Microstep Optix MAG27CQ 0000000000001"
workspace 16 output "Microstep Optix MAG27CQ 0000000000001"
workspace 17 output "Microstep Optix MAG27CQ 0000000000001"
workspace 18 output "Microstep Optix MAG27CQ 0000000000001"
workspace 19 output "Microstep Optix MAG27CQ 0000000000001"
workspace 20 output "Microstep Optix MAG27CQ 0000000000001"

workspace 1 output "LG Electronics LG HDR 4K 0x00008FEE"
workspace 2 output "LG Electronics LG HDR 4K 0x00008FEE"
workspace 3 output "LG Electronics LG HDR 4K 0x00008FEE"
workspace 4 output "LG Electronics LG HDR 4K 0x00008FEE"
workspace 5 output "LG Electronics LG HDR 4K 0x00008FEE"
workspace 6 output "LG Electronics LG HDR 4K 0x00008FEE"
workspace 7 output "LG Electronics LG HDR 4K 0x00008FEE"
workspace 8 output "LG Electronics LG HDR 4K 0x00008FEE"
workspace 9 output "LG Electronics LG HDR 4K 0x00008FEE"
workspace 10 output "LG Electronics LG HDR 4K 0x00008FEE"

output "DENON, Ltd. DENON-AVR 0000000000001" {
  mode 1920x1080
  position -1920,1080
}

output "Microstep Optix MAG27CQ 0000000000001" {
  mode 2560x1440@143.995Hz
  # position 3104,306
  position 3840,380
}

output "LG Electronics LG HDR 4K 0x00008FEE" {
  mode 3840x2160@59.997Hz
  position 0,0
  # scale 1.2371134
}

input "type:keyboard" {
  xkb_layout us
}

gaps inner 12
gaps outer 14
