workspace 1 output "Chimei Innolux Corporation 0x1239 0x00000000"
workspace 2 output "Chimei Innolux Corporation 0x1239 0x00000000"
workspace 3 output "Chimei Innolux Corporation 0x1239 0x00000000"
workspace 4 output "Chimei Innolux Corporation 0x1239 0x00000000"
workspace 5 output "Chimei Innolux Corporation 0x1239 0x00000000"
workspace 6 output "Chimei Innolux Corporation 0x1239 0x00000000"
workspace 7 output "Chimei Innolux Corporation 0x1239 0x00000000"
workspace 8 output "Chimei Innolux Corporation 0x1239 0x00000000"
workspace 9 output "Chimei Innolux Corporation 0x1239 0x00000000"
workspace 10 output "Chimei Innolux Corporation 0x1239 0x00000000"

output "Chimei Innolux Corporation 0x1239 0x00000000" {
  mode 1920x1080
  position 0,0
}

input "type:keyboard" {
  xkb_layout de
}

gaps inner 4
gaps outer 6
