mode "volume" {
  bindsym j exec pamixer --decrease 1
  bindsym k exec pamixer --increase 1
  bindsym Shift+j exec pamixer --decrease 10
  bindsym Shift+k exec pamixer --increase 10

  bindsym Return mode "default"
  bindsym Escape mode "default"
}

mode "microphone" {
  bindsym XF86AudioRaiseVolume exec pamixer --default-source --increase 1
  bindsym XF86AudioLowerVolume exec pamixer --default-source --decrease 1
  bindsym Shift+XF86AudioRaiseVolume exec pamixer --default-source --increase 10
  bindsym Shift+XF86AudioLowerVolume exec pamixer --default-source --decrease 10

  bindsym Return mode "default"
  bindsym Escape mode "default"
}
