mode "gaps inner" {
  bindsym plus gaps inner current plus 1
  bindsym minus gaps inner current minus 1
  bindsym 0 gaps inner current set 0

  bindsym Shift+plus gaps inner all plus 1
  bindsym Shift+minus gaps inner all minus 1
  bindsym Shift+0 gaps inner all set 0

  bindsym Return mode "default"
  bindsym Escape mode "default"
}

mode "gaps outer" {
  bindsym plus gaps outer current plus 1
  bindsym minus gaps outer current minus 1
  bindsym 0 gaps outer current set 0

  bindsym Shift+plus gaps outer all plus 1
  bindsym Shift+minus gaps outer all minus 1
  bindsym Shift+0 gaps outer all set 0

  bindsym Return mode "default"
  bindsym Escape mode "default"
}

mode "gaps" {
  bindsym o mode "gaps outer"
  bindsym i mode "gaps inner"

  bindsym Return mode "default"
  bindsym Escape mode "default"
}
