mode "mpc volume" {
  bindsym j exec mpc volume -1
  bindsym k exec mpc volume +1
  bindsym Shift+j exec exec mpc volume -10
  bindsym Shift+k exec exec mpc volume +10

  bindsym Return mode "default"
  bindsym Escape mode "default"
}

mode "mpc" {
  bindsym XF86AudioRaiseVolume exec mpc volume +1
  bindsym XF86AudioLowerVolume exec mpc volume -1
  bindsym Shift+XF86AudioRaiseVolume exec mpc volume +10
  bindsym Shift+XF86AudioLowerVolume exec mpc volume -10

  bindsym j exec mpc next
  bindsym k exec mpc prev

  bindsym c exec mpc toggle

  bindsym o exec mpc consume on
  bindsym Shift+o exec mpc consume off

  bindsym 1 exec mpc single on
  bindsym Shift+1 exec mpc single off

  bindsym r exec mpc random on
  bindsym Shift+r exec mpc random off

  bindsym p exec mpc stop

  bindsym s exec mpc shuffle

  bindsym h exec mpc seek -00:00:01
  bindsym l exec mpc seek +00:00:01
  bindsym Shift+h exec mpc seek -00:00:10
  bindsym Shift+l exec mpc seek +00:00:10

  bindsym v mode "mpc volume"

  bindsym Return mode "default"
  bindsym Escape mode "default"
}
